In [1]:
a**5

NameError: name 'a' is not defined

In [2]:
5**5

3125

In [ ]:
5+5

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
pip install numpy


     |████████████████████████████████| 14.5 MB 1.2 MB/s eta 0:00:01     |████████████████████████▎       | 11.0 MB 691 kB/s eta 0:00:06     |██████████████████████████████▎ | 13.8 MB 1.9 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np


In [6]:
ar = [i for i in range(5,25)]

In [7]:
np_arr = np.array(ar)

In [8]:
np.mean(np_ar)

NameError: name 'np_ar' is not defined

In [9]:
np.mean(np_arr)

14.5

In [51]:
np_ar = np.array([2,6,2,8,4,0,1,5,7])

In [47]:
np.nanmean(np_ar)

3.888888888888889

In [52]:
matrix = []
for i in range(0, 9, 3):
    matrix.append([np_ar[i], np_ar[i+1], np_ar[i+2]])
    

In [53]:
matrix


[[2, 6, 2], [8, 4, 0], [1, 5, 7]]

In [54]:
nump_matrix = np.array(matrix)

In [43]:
np.mean(nump_matrix)

3.888888888888889

In [59]:
a = np.mean(nump_matrix, axis=0)

In [60]:
np.set_printoptions(precision=16)

In [61]:
a


array([3.6666666666666665, 5.                , 3.                ])

In [62]:
a = np.mean(nump_matrix, axis=1, keepdims=True)

In [63]:
a


array([[3.3333333333333335],
       [4.                ],
       [4.333333333333333 ]])

In [49]:
np.mean(nump_matrix)

3.888888888888889

In [64]:
[np.std(nump_matrix, axis=0), np.std(nump_matrix, axis=1), np.std(nump_matrix)]


[array([3.091206165165235, 0.816496580927726, 2.943920288775949]),
 array([1.8856180831641267, 3.265986323710904 , 2.494438257849294 ]),
 2.6434171674156266]

In [65]:
[np.var(nump_matrix, axis=0), np.var(nump_matrix, axis=1), np.var(nump_matrix)]


[array([9.555555555555557 , 0.6666666666666666, 8.666666666666666 ]),
 array([ 3.555555555555556, 10.666666666666666,  6.222222222222221]),
 6.987654320987654]

In [66]:
[np.max(nump_matrix, axis=0), np.max(nump_matrix, axis=1), np.max(nump_matrix)]


[array([8, 6, 7]), array([6, 8, 7]), 8]

In [67]:
[np.min(nump_matrix, axis=0), np.min(nump_matrix, axis=1), np.min(nump_matrix)]

[array([1, 4, 0]), array([2, 0, 1]), 0]

In [68]:
[np.sum(nump_matrix, axis=0), np.sum(nump_matrix, axis=1), np.sum(nump_matrix)]

[array([11, 15,  9]), array([10, 12, 13]), 35]